all:
	gcc -std=gnu11 -O3 -o bidding_system bidding_system.c
	g++ -std=gnu++14 -O3 -o bidding_system_EDF bidding_system_EDF.cpp
	g++ -std=gnu++14 -O0 -o customer customer.cpp
clean:
	rm bidding_system
	rm bidding_system_EDF
	rm customer
